### ISSUE TITLE
ordino-daily is not up-to-date 

### ISSUE THREAD

**Issue by oltionchampari** [Caleydo/ordino_public#132]
* Release number or git hash: develop branch
* Web browser version and OS: chrome
* Environment (local or deployed): deployed

### Steps to reproduce

1. Go to https://ordino-daily.caleydoapp.org/app/#clue_graph=ordino238

### Observed behavior
* version is not up-to-date 

### Comment 
* Caused by AWS org switch (probably)

**Comment by keckelt** [comment]
Fixed via https://github.com/Caleydo/ordino_product/pull/65

![image](https://user-images.githubusercontent.com/10337788/153849951-88c27bf7-6208-41ef-b7b1-8b9648b87f56.png)
